package com.model.types;

public enum Brand {
    ACER, APPLE, ASUS, BOSCH, DELL, JBL, KIVI, LENOVO, LG, MEIZU, MOULINEX, PANASONIC, PHILIPS,
    SAMSUNG, SUUNTO, TOSHIBA, XIAOMI, ZANUSSI, ZELMER, ZTE
}
